// packages/solid/src/index.ts
import { createSignal, onCleanup } from 'solid-js';
import type { AIStore, AIFullState, Message, ToolCallState, DeepPartial } from '@store-ai/core';

export interface UseAIReturn<T = unknown> {
  state: () => AIFullState<T>;
  text: () => string;
  status: () => AIFullState<T>['status'];
  messages: () => Message[];
  toolCalls: () => ToolCallState[];
  thinking: () => string;
  error: () => Error | null;
  isStreaming: () => boolean;
  partialObject: () => DeepPartial<T> | null;
  object: () => T | null;
}

/**
 * Creates reactive Solid accessors from an AIStore.
 *
 * Must be called within a reactive scope (component body, `createRoot`, etc.)
 * so that `onCleanup` can automatically unsubscribe when the scope is disposed.
 */
export function useAI<T = unknown>(store: AIStore<T>): UseAIReturn<T> {
  const [state, setState] = createSignal<AIFullState<T>>(store.get());

  const unsub = store.subscribe((s) => setState(() => s));
  onCleanup(unsub);

  return {
    state,
    text: () => state().text,
    status: () => state().status,
    messages: () => state().messages,
    toolCalls: () => state().toolCalls,
    thinking: () => state().thinking,
    error: () => state().error,
    isStreaming: () => state().isStreaming,
    partialObject: () => state().partialObject,
    object: () => state().object,
  };
}

// packages/react/src/index.ts
import { useSyncExternalStore, useCallback } from 'react';
import type { AIStore, AIFullState, Message, ToolCallState, DeepPartial } from '@store-ai/core';

export function useAIStore<T, S>(store: AIStore<T>, selector: (state: AIFullState<T>) => S): S {
  return useSyncExternalStore(
    useCallback((cb) => store.subscribe(cb), [store]),
    () => selector(store.get()),
    () => selector(store.get()), // server snapshot same as client
  );
}

export function useAIText(store: AIStore): string {
  return useAIStore(store, (s) => s.text);
}

export function useAIStatus(store: AIStore): AIFullState['status'] {
  return useAIStore(store, (s) => s.status);
}

export function useAIMessages(store: AIStore): Message[] {
  return useAIStore(store, (s) => s.messages);
}

export function useAIToolCalls(store: AIStore): ToolCallState[] {
  return useAIStore(store, (s) => s.toolCalls);
}

export function useAIObject<T>(store: AIStore<T>): DeepPartial<T> | null {
  return useAIStore(store, (s) => s.partialObject);
}

export function useAIThinking(store: AIStore): string {
  return useAIStore(store, (s) => s.thinking);
}

export function useAIIsStreaming(store: AIStore): boolean {
  return useAIStore(store, (s) => s.isStreaming);
}

export function useAIError(store: AIStore): Error | null {
  return useAIStore(store, (s) => s.error);
}
